### ISSUE TITLE
Support IndexedDB as storage option

### ISSUE THREAD

**Issue by TomDeSmet** [prazdevs/pinia-plugin-persistedstate#110]
### Clear and concise description of the problem

I don't think IndexedDB is supported now as I can't add it as the storage option in the plugin config?
I'm using this plugin to store some larger data sets inside a hybrid iOS built app (using Ionic/Capacitor), that are to small to store in SQLlite, but need to be consistently available.
As LocalStorage can be cleared by the browser anytime and IndexedDB doesn't suffer that fate (so I've read) and is more targeted towards larger datasets, it would be nice to be able to choose that one.

### Suggested solution

Add IndexedDB as a storage option.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
As talked about in #17 , the issue lies within how pinia's `$subscribe` works synchronously. There is no way (or none that I am aware of) to have a consistent async persistence API that wont involve desync or potential race conditions.

This can not be considered at the moment, but will be if Pinia ever allows async behaviour (which is restricted to actions for now, which you can look into to persist data asynchronously).

😞
