### ISSUE TITLE
Version control support

### ISSUE THREAD

**Issue by preflower** [prazdevs/pinia-plugin-persistedstate#215]
### Clear and concise description of the problem

version control is a great feature that help developer incrementally update local data;

### Suggested solution

we can refer to zustand persist api
- version
	- description: current version
- migrate: (state, version) => state
	- description: developer can compare version to provide migrate solutions

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by prazdevs** [comment]
I dont really understand what is expected from this plugin ?
This is just a pinia plugin , not pinia itself, so i can't really see the comparison with zustand 🤔

**Comment by preflower** [comment]
> I dont really understand what is expected from this plugin ? This is just a pinia plugin , not pinia itself, so i can't really see the comparison with zustand 🤔

we talking about it's plugin function not pinia itself; maybe I didn't say it clearly, we can [refer](https://docs.pmnd.rs/zustand/integrations/persisting-store-data#version) zustand persist middware(just like pinia plugin), it support these feature.

**Comment by prazdevs** [comment]
I kind of get the idea now, but it's far beyond the scope of this plugin. The aim of the plugin is to remain simple and avoid exposing too much complexity. Since it doesnt have full control over state (that's pinia's job), it can also lead to problems later.
You could maybe achieve versionning through a custom storage? 
But there is definitely no plan in adding something as complex as zustand.
