### ISSUE TITLE
Vue: Argument of type

### ISSUE THREAD

**Issue by jtyoui** [prazdevs/pinia-plugin-persistedstate#299]
### Describe the bug

![image](https://github.com/prazdevs/pinia-plugin-persistedstate/assets/28988355/ba0f1276-4389-4276-9bbc-ceb004a1797d)

### Reproduction

3.2.1

### System Info

```Shell
Window
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
will need a proper reproduction to investigate (a gh repo or stackblitz)

**Comment by alongw** [comment]
I had the same problem, but I made it work by adding "types":". in package.json of pinia-plugins-persistedstate. /dist/index.d.ts" in the package.json to fix it.

**Comment by alongw** [comment]
Are you using https://github.com/Seb-L/pinia-plugin-persist? They are different plugins.

I had the same problem with that plugin, by adding `"types": ". /dist/index.d.ts"` line of code in the `package.json` file solved it, but I've now switched to the plugin in the current repository. Because he hasn't been updated for two years.
