### ISSUE TITLE
Initial state is not persisted

### ISSUE THREAD

**Issue by Xexnon** [prazdevs/pinia-plugin-persistedstate#5]
The inital state of the store is not persisted. Only when the data is changed is the state persisted

**Comment by prazdevs** [comment]
Well, that's also the behaviour of `vuex-persistedstate`. I don't really understand why you would need to persist the initial state, since it is the initial state: rehydrating initial data seems to be pointless. I'm open to improvement, so if you have an interesting use case for this feature, I could work on it.

**Comment by prazdevs** [comment]
Closing this for now. If it seems like something needed, I may reconsider it.
