### ISSUE TITLE
Could you please provide the document of config of storage?

### ISSUE THREAD

**Issue by KahrLu** [prazdevs/pinia-plugin-persistedstate#73]
![image](https://user-images.githubusercontent.com/76502123/171157480-94b3b5b3-dc5d-4fe6-8c8d-8ceb5eb70054.png)
I don't know how to write here or what options are available. The details are not mentioned in the current documents and examples. Could you please add them?

**Comment by prazdevs** [comment]
Hi, your question is more related to Nuxt and SSR :)

What is happening is that you configured the plugin as a server AND client Nuxt plugin. The problem is when doing server side rendering, Nuxt does not have access to brower-side APIs (localStorage or window are client-side only).

If you change your plugin to be client-only (myplugin.client.ts), it should work, but will not apply persistence while doing the server-side rendering. 

That's why we provide a nuxt helper that makes use of Cookies, usable both server AND client side :)

**Comment by KahrLu** [comment]
> Hi, your question is more related to Nuxt and SSR :)
> 
> What is happening is that you configured the plugin as a server AND client Nuxt plugin. The problem is when doing server side rendering, Nuxt does not have access to brower-side APIs (localStorage or window are client-side only).
> 
> If you change your plugin to be client-only (myplugin.client.ts), it should work, but will not apply persistence while doing the server-side rendering.
> 
> That's why we provide a nuxt helper that makes use of Cookies, usable both server AND client side :)

yes, but cookies are limited in length. The last time I encountered the problem that the object type could not be saved to the cookie, the reason was that the object data was too large.

**Comment by prazdevs** [comment]
If the data you store is only used client-side, you can always use a localStorage by making the plugin a client-side only plugin.

**Comment by KahrLu** [comment]
thanks! @prazdevs
